apiVersion: v1
kind: Namespace
metadata:
  name: cluster-relocation
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-relocation-service
  namespace: cluster-relocation
  labels:
    app: cluster-relocation
spec:
  selector:
    matchLabels:
      app: cluster-relocation
  replicas: 1
  template:
    metadata:
      labels:
        app: cluster-relocation
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        image: quay.io/carbonin/cluster-relocation-service:latest
        name: manager
        env:
        - name: SERVICE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SERVICE_NAME
          value: cluster-relocation-config
        - name: SERVICE_PORT
          value: "8000"
        - name: SERVICE_SCHEME
          value: "https"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - name: data
          mountPath: /data
      - command:
        - /server
        image: quay.io/carbonin/cluster-relocation-service:latest
        name: server
        env:
        - name: HTTPS_KEY_FILE
          value: /certs/tls.key
        - name: HTTPS_CERT_FILE
          value: /certs/tls.crt
        - name: PORT
          value: "8000"
        ports:
        - name: config-server
          containerPort: 8000
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - name: data
          mountPath: /data
        - name: certs
          mountPath: /certs
      volumes:
      - name: data
        emptyDir: {}
      - name: certs
        secret:
          secretName: cluster-relocation-server
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-relocation-config
  namespace: cluster-relocation
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: cluster-relocation-server
spec:
  ports:
  - port: 8000
    protocol: TCP
    name: config-server
  selector:
    app: cluster-relocation
